import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router-dom";
import { expect, it, vi } from "vitest";
import { api } from "../api/client";
import { App } from "../routes/App";
import type { Asset, Project, Render, Shot, Variant } from "../types";

it("shows Tour provenance, generates mock variants, and persists selection", async () => {
  const project: Project = { id: "tour", project_type: "TOUR_GUIDE", title: "Beograd POV", creative_brief: "Vertikalni POV putopis kroz Beograd", aspect_ratio: "9:16", status: "DRAFT", created_at: "x", updated_at: "x" };
  let selected = false;
  let assets: Asset[] = [];
  const shot: Shot = { id: "shot-1", ordinal: 1, title: "Kalemegdan", prompt: "POV walk", intended_duration: 8, status: "PLANNED", selected_variant_id: null, source_plan_id: "plan-2", source_plan_item_key: "scene-001", source_plan_version: 2, source_scene_duration: 8, source_location_or_motif: "Kalemegdan", source_pov_description: "Prilazak vidikovcu iz prvog lica", source_narration: "Stižemo do pogleda na ušće.", source_factual_claims: [{ claim: "Pogled na ušće", sources: ["https://example.test/source"] }] };
  const variant: Variant = { id: "variant-1", mime_type: "video/mp4", duration: 8, review_status: "UNREVIEWED", created_at: "x", generation_attempt_id: "attempt-1", attempt_number: 1, job_id: "job-1", provider: "mock", model: "mock-video-v1", generation_mode: "text-to-video", plan_provenance: { source_plan_id: "plan-2", source_plan_version: 2, source_plan_item_key: "scene-001" } };
  vi.spyOn(api, "project").mockResolvedValue(project);
  vi.spyOn(api, "assets").mockImplementation(async () => assets);
  vi.spyOn(api, "uploadVoiceover").mockImplementation(async () => { assets = [{ id: "voice-1", asset_type: "VOICEOVER", filename: "voice.wav", mime_type: "audio/wav", size_bytes: 100, checksum: "checksum", rights_metadata: {}, created_at: "x", shot_id: shot.id, source_plan_id: "plan-2", source_plan_version: 2, source_plan_item_key: "scene-001", narration_checksum: "narration", media_duration: 6.5 }]; return { id: "voice-1", shot_id: shot.id, duration: 6.5, mime_type: "audio/wav" }; });
  vi.spyOn(api, "shots").mockImplementation(async () => [{ ...shot, selected_variant_id: selected ? variant.id : null, latest_job_status: selected ? "SUCCEEDED" : null }]);
  vi.spyOn(api, "generate").mockResolvedValue({ job_id: "job-1", status: "QUEUED" });
  vi.spyOn(api, "job").mockResolvedValue({ id: "job-1", status: "SUCCEEDED", retry_count: 0, error_data: null, created_at: "x", started_at: "x", completed_at: "x" });
  vi.spyOn(api, "variants").mockImplementation(async () => [{ ...variant, review_status: selected ? "SELECTED" : "UNREVIEWED" }]);
  vi.spyOn(api, "selectVariant").mockImplementation(async () => { selected = true; return {}; });
  vi.spyOn(api, "rejectVariant").mockResolvedValue({});
  vi.spyOn(api, "tourTimeline").mockResolvedValue({ items: [{ shot_id: shot.id, ordinal: 1, title: shot.title, shot_duration: 8, start_seconds: 0, end_seconds: 8, selected_variant_id: variant.id, narration: shot.source_narration!, voiceover_asset_id: "voice-1", voiceover_duration: 6.5, voiceover_status: "READY", ready: true }], total_duration: 8, ready: true, next_render_requirements: ["opening title", "closing title", "music bed"] });

  render(<MemoryRouter initialEntries={["/projects/tour/shots"]}><App/></MemoryRouter>);
  expect((await screen.findAllByText("Kalemegdan"))[0]).toBeVisible();
  expect(screen.getByText("Prilazak vidikovcu iz prvog lica")).toBeVisible();
  expect(screen.getByText(/Stižemo do pogleda/)).toBeVisible();
  expect(screen.getByRole("link", { name: "https://example.test/source" })).toBeVisible();
  expect(screen.getByText("Mock visual · no paid provider")).toBeVisible();
  expect(screen.queryByText("Add planned shot")).not.toBeInTheDocument();
  expect(screen.queryByLabelText("Reference image for shot 1")).not.toBeInTheDocument();
  await userEvent.upload(screen.getByLabelText("Voiceover for shot 1"), new File(["voice"], "voice.wav", { type: "audio/wav" }));
  await userEvent.click(screen.getByRole("button", { name: "Upload voiceover" }));
  await waitFor(() => expect(screen.getByText("6.50s audio / 8.00s shot")).toBeVisible());
  await userEvent.click(screen.getByRole("button", { name: "Generate variant" }));
  expect(await screen.findByRole("button", { name: "Generate another" })).toBeVisible();
  await userEvent.click(screen.getByRole("button", { name: "Generate another" }));
  expect(api.generate).toHaveBeenCalledTimes(2);

  await userEvent.click(screen.getByRole("link", { name: /Review$/ }));
  await userEvent.click(await screen.findByRole("button", { name: "Select" }));
  await waitFor(() => expect(screen.getByText("Current selection")).toBeVisible());
  expect((await api.shots(project.id))[0].selected_variant_id).toBe(variant.id);
  await userEvent.click(screen.getByRole("link", { name: /Timeline$/ }));
  expect(await screen.findByText("Tour timing")).toBeVisible();
  expect(screen.getByText("Total 8.00s")).toBeVisible();
  expect(screen.getByText("Ready for Tour render implementation")).toBeVisible();
  expect(screen.getByText("music bed")).toBeVisible();
});

it("uploads licensed Tour music and submits a persisted render preview", async () => {
  const project: Project = { id: "tour", project_type: "TOUR_GUIDE", title: "Beograd POV", creative_brief: "Vertikalni POV putopis kroz Beograd", aspect_ratio: "9:16", status: "DRAFT", created_at: "x", updated_at: "x" };
  let music: Asset | undefined;
  const completed: Render = { id: "render-1", status: "SUCCEEDED", output_storage_key: "tour.mp4", mime_type: "video/mp4", duration: 8, error_data: null, render_spec: { render_type: "TOUR_GUIDE", expected_duration: 8, opening_title: "Beograd POV", closing_title: "Kraj", incomplete_demo_preview: false, source_plan_version: 2 }, created_at: "x", started_at: "x", completed_at: "x" };
  vi.spyOn(api, "project").mockResolvedValue(project);
  vi.spyOn(api, "tourTimeline").mockResolvedValue({ items: [{ shot_id: "shot-1", ordinal: 1, title: "Kalemegdan", shot_duration: 8, start_seconds: 0, end_seconds: 8, selected_variant_id: "variant-1", narration: "Naracija", voiceover_asset_id: "voice-1", voiceover_duration: 6, voiceover_status: "READY", ready: true }], total_duration: 8, ready: true, next_render_requirements: [] });
  vi.spyOn(api, "assets").mockImplementation(async () => music ? [music] : []);
  vi.spyOn(api, "renders").mockResolvedValue([]);
  vi.spyOn(api, "uploadTourMusic").mockImplementation(async () => { music = { id: "music-1", asset_type: "TOUR_MUSIC", filename: "licensed.wav", mime_type: "audio/wav", size_bytes: 10, checksum: "music", rights_metadata: { usage_confirmed: true }, media_duration: 20, created_at: "x" }; return { id: music.id, duration: 20, mime_type: music.mime_type }; });
  vi.spyOn(api, "submitTourRender").mockResolvedValue({ ...completed, status: "QUEUED", output_storage_key: null, duration: null });
  vi.spyOn(api, "render").mockResolvedValue(completed);
  render(<MemoryRouter initialEntries={["/projects/tour/render"]}><App/></MemoryRouter>);
  expect(await screen.findByText("Final vertical video")).toBeVisible();
  expect(screen.getByText(/incomplete demo preview/)).toBeVisible();
  await userEvent.upload(screen.getByLabelText("Tour music file"), new File(["music"], "licensed.wav", { type: "audio/wav" }));
  await userEvent.click(screen.getByText("I confirm usage rights for this music"));
  await userEvent.click(screen.getByRole("button", { name: "Upload music" }));
  expect(await screen.findByText("licensed.wav")).toBeVisible();
  await userEvent.type(screen.getByLabelText("Closing title"), "Kraj");
  await userEvent.click(screen.getByRole("button", { name: "Render Tour MP4" }));
  await waitFor(() => expect(api.submitTourRender).toHaveBeenCalledWith("tour", { opening_title: "Beograd POV", closing_title: "Kraj", music_asset_id: "music-1" }));
  expect(await screen.findByText("Tour output")).toBeVisible();
  expect(screen.getByRole("link", { name: "Download MP4" })).toHaveAttribute("href", expect.stringContaining("download=true"));
});
