from typing import Protocol

from backend.app.domain.models import GenerationRequest, GenerationResult, GenerationStatus


class VideoProvider(Protocol):
    def submit_generation(self, request: GenerationRequest) -> str: ...
    def get_status(self, provider_job_id: str) -> GenerationStatus: ...
    def get_result(self, provider_job_id: str) -> GenerationResult: ...
    def cancel(self, provider_job_id: str) -> GenerationStatus: ...
